<?php
// $Id$
/**
	* @file
	* A custom module
	*/
//drupal_flush_all_caches();	
/** 
 * Implement hook_menu(). 
 */ 
function cals_forms_menu() { 
	$items = array();
 
	return $items;
}	

 

/* ----------- The forms ------------ */
/**
 * Implements hook_form_alter().
 */
function cals_forms_form_alter(&$form, &$form_state, $form_id) {
	
	switch($form_id) {

		case "calsauthen_edit_target":
		case "calsauthen_add_target":
			
			$qry = db_query("SELECT distinct n.nid, n.title, fd.*, fa.field_address_administrative_area as prov 
				FROM {field_data_field_organization} fd inner join {node} n on fd.field_organization_nid = n.nid 
				  inner join {field_data_field_address} fa on fa.entity_id = n.nid
				  inner join {field_data_field_target} ft on ft.entity_id = n.nid
				WHERE fd.entity_type = :value
				order by fa.field_address_administrative_area, n.title", 
				array(":value" => "user")
			);		
			$options = array();
			
			foreach($qry as $row) {
				$options[$row->prov][$row->nid] = $row->title;
			}
			$form['node']['#options'] = $options;
			$form['node']['#description'] = t("Only libraries tagged as a Target will be displayed in this list");
			//printAndDie($options, $form);		
			break;
		
		case "views_exposed_form":
    	//$form['search_api_views_fulltext_2']['#attributes'] = array('placeholder' => t('Search for author, title, description'));


			if($form['#id'] == 'views-exposed-form-cals-users-page') {
				
				//limit org field to just orgs associated with existing users.
				//this limits list to manageable number.

				$qry = db_query("SELECT distinct n.nid, n.title, fd.*, fa.field_address_administrative_area as prov 
					FROM {field_data_field_organization} fd inner join {node} n on fd.field_organization_nid = n.nid 
					  inner join {field_data_field_address} fa on fa.entity_id = n.nid
					WHERE fd.entity_type = :value
					order by fa.field_address_administrative_area, n.title", 
					array(":value" => "user")
				);
			  //build options
			  $options = array(t("All") => t("-Any-"));
			  
			  foreach($qry as $row) {
			  
			  	$options[$row->prov][$row->nid] = $row->title;
			  
			  }
			  //printAndDie($options);
			  
			  $form['field_organization_nid']['#options'] = $options;
			}

			break;
		case "views_form_cals_users_page":
			//printAndDie($form);
			//dpm($form['field_organization']);
		
			break;
		case "post_node_formx":
			$group = og_context($group_type = 'node', $group = NULL);
			//dpm($group);
			if(!$group) {
				drupal_set_message("You need to be posting via a group", "error");
			  //drupal_access_denied("oops, need to be posting from a group");
			}
			if(!is_numeric($form['nid']['#value']) ) {
				
				//$form['og_group_ref']['und'][0]['default']['#default_value']
				//unset($form['og_group_ref']); //['#type']); // = 'value';
				$form['og_group_ref']['und']['#title'] = '';
				unset($form['og_group_ref']['und']['#prefix']);
				unset($form['og_group_ref']['und']['#suffix']);
				$form['og_group_ref']['und'][0]['default']['#default_value'] = $group['gid'];
				$form['og_group_ref']['und'][0]['default']['#type'] = 'value';
				//$form['og_group_ref']['und'][0]['admin']['#type'] = 'value';
			}
			//dpm($form['og_group_ref']['und'][0]['default']);
			break;
		
	}

}